name: Generation
version: '${version}'
main: dev.akex.generation.Generation
api-version: 1.19
load: STARTUP

commands:
  generateworld:
    aliases:
      - genworld
    permission: generation.world.generate